##
## WARNING! This configuration file covers only Axon and nRF Edge AI related settings. 
## It is not a complete configuration file and should be used as an overlay on top of an application configuration file (e.g. prj.conf) that includes all the necessary settings for your application.
##
# nRF Edge AI
CONFIG_NRF_EDGEAI=y
# nRF Edge AI dependencies
CONFIG_NEWLIB_LIBC=y
CONFIG_FPU=y
# nRF Axon
CONFIG_NRF_AXON=y
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=6048
CONFIG_NRF_AXON_PSUM_BUFFER_SIZE=0
